# Generated by Django 4.1.5 on 2023-03-27 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessons',
            options={'verbose_name': 'درس', 'verbose_name_plural': 'درس\u200cها'},
        ),
    ]
