# Generated by Django 4.1.5 on 2023-03-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons_module', '0002_alter_lessons_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='image',
            field=models.ImageField(default='', upload_to='images/lessons/', verbose_name='عکس کاور'),
            preserve_default=False,
        ),
    ]
