# Generated by Django 4.1.5 on 2023-03-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons_module', '0003_lessons_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='id',
        ),
        migrations.AddField(
            model_name='lessons',
            name='id_lesson',
            field=models.IntegerField(default=1, primary_key=True, serialize=False, verbose_name='شماره درس'),
            preserve_default=False,
        ),
    ]
