# Generated by Django 4.1.5 on 2023-03-28 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons_module', '0004_remove_lessons_id_lessons_id_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='lessons_module.lessons', verbose_name='درس')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کابر')),
            ],
            options={
                'verbose_name': 'درس خوانده شده کاربر',
                'verbose_name_plural': 'درس های خوانده شده کاربران',
            },
        ),
    ]
