# Generated by Django 4.1.5 on 2023-03-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=300, verbose_name='نام سایت')),
                ('email', models.EmailField(max_length=350, verbose_name='ایمیل')),
                ('about_us', models.TextField(verbose_name='دربارۀ ما')),
                ('copyright', models.TextField(max_length=600, verbose_name='متن کپی رایت')),
                ('logo', models.ImageField(upload_to='images/logo', verbose_name='لوگوی سایت')),
                ('is_main_setting', models.BooleanField(verbose_name='تنظیمات اصلی سایت')),
            ],
        ),
    ]
