# Generated by Django 4.1.5 on 2023-03-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('operator_type', models.CharField(choices=[('plus', 'جمع'), ('minus', 'تفریق'), ('multiplication', 'ضرب'), ('division', 'تقسیم'), ('square', 'مجذور')], max_length=300, verbose_name='نوع عملگر')),
                ('calculations', models.CharField(max_length=500, verbose_name='محاسبات')),
                ('exercise', models.ManyToManyField(to='lessons_module.lessons', verbose_name='درس های مربوطه')),
            ],
        ),
    ]
