# Generated by Django 4.1.5 on 2023-03-27 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons_module', '0004_remove_lessons_id_lessons_id_lesson'),
        ('exercise_module', '0006_remove_exercises_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='exercise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lessons_module.lessons', verbose_name='درس مربوطه'),
        ),
    ]
