# Generated by Django 4.1.5 on 2023-03-27 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons_module', '0004_remove_lessons_id_lessons_id_lesson'),
        ('exercise_module', '0007_exercises_exercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercises',
            name='title',
        ),
        migrations.AlterField(
            model_name='exercises',
            name='exercise',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='lessons_module.lessons', verbose_name='درس مربوطه'),
            preserve_default=False,
        ),
    ]
