# Generated by Django 4.1.5 on 2023-03-28 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercise_module', '0009_rename_exercise_exercises_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsSolve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='exercise_module.exercises', verbose_name='تمرین')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تمرین انجام شدۀ کاربر',
                'verbose_name_plural': 'تمرینات انجام شدۀ کاربران',
            },
        ),
    ]
